baseURL = "/"
languageCode = "en-us"
title = "strall.com"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  author = "Ted Strall"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.assets]
  favicon = "/assets/logo/favicon-32x32.png"
  customJS = ["js/logo-theme-switch.js"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "open-source"
    name = "Open Source"
    url = "/open-source/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 99

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
